Blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('blogapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/urls.py
from django.urls import path
from . views import PostListView, PostUpdateView, PostDeleteView, PostCreateView
from . import views

app_name = 'blogapp'

urlpatterns = [
	path('', PostListView.as_view(), name='index'),
	path('myposts/', views.my_posts, name='myposts'),
	path('add_post/', PostCreateView.as_view(), name='add_post'),
	path('(?P<post_id>[0-9]+)/', views.detail, name='detail'),
	path('<int:pk>/delete/', PostDeleteView.as_view(), name='delete'),
	path('<int:pk>/update/', PostUpdateView.as_view(), name='update'),
	path('(?P<post_id>[0-9]+)/comment/', views.add_comment, name='comment'),
	path('register/', views.register, name='register'),
	path('login/', views.login_user, name='login'),
	path('logout/', views.logout_user, name='logout'),
]

blogapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.shortcuts import reverse


# Create your models here.
class Post(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=45)
	image = models.FileField()
	content = models.TextField()
	created = models.DateTimeField(default=timezone.now)

	def get_absolute_url(self):
		return reverse('blogapp:index')

	def __str__(self):
		return self.title


class Comment(models.Model):
	user = models.ForeignKey(User, on_delete=models.PROTECT)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	comment = models.TextField()
	created = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.comment

blogapp/forms.py
from django.contrib.auth.models import User
from django import forms
from . models import Comment


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['comment']


class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username', 'email', 'password']

blogapp/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views.generic import ListView, DeleteView, UpdateView, CreateView
from . models import Post, Comment
from . forms import CommentForm, UserForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
class PostCreateView(LoginRequiredMixin, CreateView):
	model = Post
	fields = ['title', 'image', 'content']

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super().form_valid(form)


class PostListView(ListView):
	model = Post
	context_object_name = 'posts'
	ordering = ['-created']
	template_name = 'blogapp/index.html'


def my_posts(request):
	posts = Post.objects.filter(user=request.user)
	return render(request, 'blogapp/index.html', {'posts': posts})


def detail(request, post_id):
	form = CommentForm(request.POST or None)
	post = get_object_or_404(Post, pk=post_id)
	return render(request, 'blogapp/detail.html', {'post': post, 'form': form})


@login_required(login_url='blogapp:login')
def add_comment(request, post_id):
	form = CommentForm(request.POST or None)
	post = get_object_or_404(Post, pk=post_id)
	if form.is_valid():
		comment = form.save(commit=False)
		comment.post = post
		comment.user = request.user
		comment.save()
		return render(request, 'blogapp/detail.html', {'post': post})
	form = CommentForm()
	return render(request, 'blogapp/detail.html', {'form': form})


class PostUpdateView(UpdateView):
	model = Post
	fields = ['title', 'image', 'content']
	template_name = 'blogapp/post_update.html'

	def get_success_url(self):
		return reverse('blogapp:index')

	def form_valid(self, form):
		return super().form_valid(form)


class PostDeleteView(DeleteView):
	model = Post
	success_url = '/'


def register(request):
	form = UserForm(request.POST or None)
	if form.is_valid():
		user = form.save(commit=False)
		username = form.cleaned_data['username']
		password = form.cleaned_data['password']
		user.set_password(password)
		user.save()
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				posts = Post.objects.filter(user=request.user)
				context = {
					'posts': posts,
					'message': 'Account Created Successful! '
				}
				return render(request, 'blogapp/index.html', context)
	context = {
		'form': form,
	}
	return render(request, 'blogapp/register.html', context)


def login_user(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				posts = Post.objects.filter(user=request.user)
				context = {
					'posts': posts
				}
				return render(request, 'blogapp/index.html', context)
	return render(request, 'blogapp/login.html')


def logout_user(request):
	logout(request)
	return redirect('blogapp:login')

blogapp/templates/blogapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}BlogCast{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="#"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'blogapp/css/main.css' %}" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'blogapp:index' %}">BlogCast</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class=""><a href="{% url 'blogapp:myposts' %}"><span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; My Posts</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'blogapp:add_post' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Post
                    </a>
                </li>

                {% if user.is_authenticated %}
                <li>
                   <a href="{% url 'blogapp:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>

                {% else %}

                <li>
                    <a href="{% url 'blogapp:login' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Login
                    </a>
                </li>

                {% endif %}
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

blogapp/templates/blogapp/detail.html
{% extends 'blogapp/base.html' %}

{% block body %}
    <div class="container-fluid">
    <div class="row">
        <div class="col-sm-3">
            <div class="thumbnail">
        <img class="img img-responsive img img-thumbnail" src="{{ post.image.url }}" alt="" style="height: 350px; width: 280px;">
        <div class="caption">
            <h4>{{ post.title }}</h4>
            <h5> <strong>Author: </strong><small style="color: darkcyan; font-size: 14px;"> {{ post.user }} </small></h5>
        </div>
            </div>
    </div>

        <div class="col-sm-8">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li class="active"><a href="">Read</a> </li>
                <li class=""> <a href="" data-toggle="modal" data-target="#myModal">comment</a> </li>
            </ul>

            <div class="panel panel-primary">
                <div class="panel-body">
                    <h4 class=""><b>{{ post.title }}</b> {% if request.user == post.user %}
                    <a href="{% url 'blogapp:update' post.pk %}" class="btn btn-primary btn-sm">
                        <span class="glyphicon glyphicon-pencil"></span>&nbsp;
                    </a>
                    <a href="{% url 'blogapp:delete' post.pk %}" class="btn btn-danger btn-sm">
                    <span class="glyphicon glyphicon-trash"></span>&nbsp;
                    </a>
                 {% endif %}
                        <small style="float: right;">{{ post.created|date:"F d, Y" }}</small></h4>

                    <hr>
                    <P>{{ post.content }}</P>
                </div>

            </div>
            <div>
                <h5 class="text-primary"><b>Comments: &nbsp;{{ post.comment_set.count }}</b></h5>
            </div>
        {% if post.comment_set %}
            {% for comm in post.comment_set.all %}
            <p>{{ comm.comment }} <small style="float: right; color: darkcyan;">~{{ comm.user }}</small> </p>
                <hr>
            {% endfor %}
        {% endif %}

        </div>
    </div>


    <!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
<div class="modal-dialog modal-md">

<!-- Modal content-->
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title text-primary" style="padding-left: 21px;">Comment</h4>
    </div>
    <div class="modal-body">
    <form method="POST" action="{% url 'blogapp:comment' post.id %}" enctype="multipart/form-data">
    {% csrf_token %}
        {% include 'blogapp/form_template.html' %}
    <div class="form-group" style="padding-left: 107px;">
        <button type="submit" class="btn btn-info">Submit</button>
    </div>
    </form>
    </div>
    </div>
</div>
</div>
</div>


{% endblock %}

blogapp/templates/blogapp/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

blogapp/templates/blogapp/index.html
{% extends 'blogapp/base.html' %}
{% load static %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        {% if posts %}
            {% for post in posts %}
                <div class="col-sm-3">
                <div class="thumbnail">
                <a href="{% url 'blogapp:detail' post.id %}">
                <img class="img img-responsive img img-thumbnail" src="{{ post.image.url }}" alt="" style="height: 350px; width: 300px;">
                </a>

                    <div class="caption">
                    <h4>{{ post.title }} <small style="float: right;">{{ post.created|date:"F d, Y" }}</small> </h4>
                        <h5> <strong>Author: </strong><small style="color: darkcyan; font-size: 14px;">{{ post.user }}</small></h5>
                        <form method="post" action="">
                            {% csrf_token %}
                            <input type="hidden" name="album_id" value="{{ album.id }}">


                        </form>
                </div>

                </div>

                </div>
            {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

blogapp/templates/blogapp/login.html
{% extends 'blogapp/base.html' %}

{% block body %}
    <div class="container-fluid">
    <div class="row">
        <div class="col-md-4">

        </div>
        <div class="col-md-4" style="padding-top: 5%;">
            {% if message %}
                <div class="alert alert-danger">
                <strong>{{ message }}</strong>
                </div>
            {% endif %}
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3>Login</h3>
                </div>

                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" style="margin: 15px;">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label">Username:</label>
                            <input type="text" class="form-control" name="username" >
                        </div>

                        <div class="form-group">
                            <label class="control-label">Password:</label>
                            <input type="password" class="form-control" name="password" >
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Login</button>
                        </div>
                        <div>
                            <p> Not Registered? <a href="{% url 'blogapp:register' %}">Register</a></p>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
    </div>
{% endblock %}

blogapp/templates/blogapp/post_form.html
{% extends 'blogapp/base.html' %}

{% block body %}
<div class="row">
<div class="col-md-4">

</div>
    <div class="col-md-4">
        <div class="panel panel-info">
            <div class="panel-heading">
            <h3 class="text-primary" style="padding-left: 8%;"><strong>New Post</strong></h3>
        </div>

            <div class="panel-body">
                <form class="form-horizontal" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'blogapp/form_template.html' %}

                    <div class="form-group" style="padding-left: 20%;">
                    <button type="submit" class="btn btn-info">Add</button>
                    <button type="submit" class="btn btn-danger">Cancel</button>
                    </div>
                </form>
            </div>
</div>
</div>
{% endblock %}

blogapp/templates/blogapp/post_update.html
{% extends 'blogapp/base.html' %}

{% block body %}
<div class="row">
<div class="col-md-4">

</div>
    <div class="col-md-4">
        <div class="panel panel-info">
            <div class="panel-heading">
            <h3 class="text-primary" style="padding-left: 8%;"><strong>Update Post</strong></h3>
        </div>

            <div class="panel-body">
                <form class="form-horizontal" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'blogapp/form_template.html' %}

                    <div class="form-group" style="padding-left: 20%;">
                    <button type="submit" class="btn btn-info">Add</button>
                    <button type="submit" class="btn btn-danger">Cancel</button>
                    </div>
                </form>
            </div>
</div>
</div>
</div>
{% endblock %}

blogapp/templates/blogapp/register.html
{% extends 'blogapp/base.html' %}

{% block  body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">

        </div>
        <div class="col-sm-4" style="padding-top: 5%;">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="text-primary">Sign Up</h3>
                </div>
                <div class="panel-body">
                    <form method="post" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'blogapp/form_template.html' %}

                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                        <div>
                            <p>Already Registered? <a href="{% url 'blogapp:login' %}">Login</a> </p>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}